Repository courselab/ttsnake, pull requests merged in 2021-01, with the labels that each got.

#10 Improve README file
  README
  README.md
Labels: documentation

#13 Add quit to control display
  src/textronsnake.c
Labels: enhance

#14 Add scene border in code.
  scenes/game/scene-0000001.txt
  src/textronsnake.c
Labels: enhance

#18 Add Autotools' required README (link to README.md)
  README
Labels: enhance

#11 Change the main executable's name
  src/Makefile.am
  src/ttsnake.c
Labels: enhance

#25 Fix duplicated doc file.
  doc/CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#19 Change direction with WASD keys + Collision Detection
  src/ttsnake.c
Labels: +priority, enhance

#39 Improved build instructions
  README.md
Labels: documentation, good first issue

#52 Detail build & install directions
  README.md
  doc/CONTRIBUTING.md
Labels: documentation

#55 Seamlessly execute local and installed program (wrapper script)
  README.md
  configure.ac
  doc/CONTRIBUTING.md
  src/Makefile.am
  src/ttsnake.c
  src/utils.c
  src/utils.h
Labels: +priority, enhance
